### ISSUE TITLE
All in call

### ISSUE THREAD

**Issue by Romanox75** [ptwu/distributed-texasholdem#23]
Hello,

When the person who has $ 98 (1) ALL IN and the person who has $ 102 (2) Call. Whether the 1 or 2 wins but does not receive the money, the player who lost receives it.

When the person who has $ 102 (1) ALL IN and the person who has $ 98 (2) ALL IN. Whether the 1 or 2 wins but does not receive the money, the player who lost receives it.

**Comment by Identity-labs** [comment]
Same issue, with all change I have made it's more easier to fix this, test is less random.
We can set players cards & community cards to reproduce that in test.
But I don't have enough skill in poker to solve that issue, I think @ptwu can take back that last issue with that PR https://github.com/ptwu/distributed-texasholdem/pull/27

**Comment by ptwu** [comment]
Should be fixed now, along with all post-hand calculations. Feel free to open another issue @Romanox75 if you find a bug
