### ISSUE TITLE
Negative pot when 1 player disconnect

### ISSUE THREAD

**Issue by Identity-labs** [ptwu/distributed-texasholdem#30]
I have one case with negative pot when one player disconnect
If other disconnect their are loosing money
Will try to repro with unit test

If your are interested how I use the engine their it is, a game inside the game :)

https://cdn.discordapp.com/attachments/654265607096631296/724400099047768134/unknown.png
https://cdn.discordapp.com/attachments/653285819481718797/724401248392183918/unknown.png

**Comment by Identity-labs** [comment]
Can you provide help on your distributeMoney method ?
Lot of issue with 
- 1 fold in the game
- 1 all in with less money than high bet

Sum of all players money is not equal to start money always missing money
If you want talk you can add me on Discord Mido#7092

**Comment by ptwu** [comment]
I can take a look tonight or over the weekend. I might have to rethink the way I do sidepot calculations, there are some existing algorithms online that I can base it off of.

**Comment by Identity-labs** [comment]
Some times game is stuck when we have 1 or more Fold, no one can play.

**Comment by ptwu** [comment]
> Some times game is stuck when we have 1 or more Fold, no one can play.

Yeah I’ve experienced this too. The server probably shuts down because of some error/exception, need to test this

**Comment by Identity-labs** [comment]
I have fix one yesterday, try to access index of undefined

Sidepot algo : https://gist.github.com/IliasDeros/58967d2005c26ebe428ab83b13cfc864
I don't know if he is relevant

**Comment by Identity-labs** [comment]
Some time if one player leave the game (disconnect), the previous players have to play twice.
Some time entire game is stuck (no error on the server)

**Comment by ptwu** [comment]
weird. i’d say it’s probably stuck because of an infinite loop of determining who the next player to go is

**Comment by Identity-labs** [comment]
May be keep last winners data (keep username and winning money ?) in the game to make test easier we have to catch event to retrieve winner

**Comment by Identity-labs** [comment]
When all players leave the game, the pot is lost, last players don't receive it
