### ISSUE TITLE
[FEATURE] Host Server Only From Computer

### ISSUE THREAD

**Issue by windowshopr** [ptwu/distributed-texasholdem#59]
Awesome project!

Had a thought that it would be cool to host the game server only from your local machine, and NOT have it as a player also. Example, you could fire up the server on your computer in the basement, and everyone in the house could connect to the server from their phones upstairs and play the game remotely, without having someone playing physically at the computer.

Maybe once a user clicks "Host Game", there could be a checkbox for "Run Standalone Server" or something like that, where you just get the room code, first person to connect would start the game?

Would be cool to see!

**Comment by windowshopr** [comment]
And as a newbie, I just realized we can do that by simply starting the server and accessing it from another device! doh! Sorry!

**Comment by ptwu** [comment]
glad you're enjoying the project! it's been a while since i made this and there are a lot of things I would do better. hope it's been working well for your purposes :)
