### ISSUE TITLE
cannot start game when running index.html(no response when clicking get code)

### ISSUE THREAD

**Issue by zyy212121** [ptwu/distributed-texasholdem#68]
stack and have no response here
<img width="1080" alt="image" src="https://github.com/ptwu/distributed-texasholdem/assets/131937805/1f5c9966-fa14-40a7-87f9-b4f1a1cdaf19">

**Comment by Identity-labs** [comment]
Hi, did you read the README ? You have to run the server not just open the index.html

**Comment by zyy212121** [comment]
> Hi, did you read the README ? You have to run the server not just open the index.html

sorry im fish in javascript ,i dont know how to run the server, i run "yarn dev"and sth else in bash but nothing happened.
<img width="495" alt="image" src="https://github.com/ptwu/distributed-texasholdem/assets/131937805/6fb4856f-e1f2-4d99-b34b-83c1e19a5eb0">

**Comment by Identity-labs** [comment]
You have to learn how to setup nodejs environement.

**Comment by zyy212121** [comment]
> 

i try to setup nodejs,but the command is still wrong
<img width="495" alt="image" src="https://github.com/ptwu/distributed-texasholdem/assets/131937805/ed196676-a89e-44ec-85ea-c8f88499b07c">
